// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ticket/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ticket "github.com/dilaragorum/ticket-api/internal/ticket"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateTicketOption mocks base method.
func (m *MockRepository) CreateTicketOption(ctx context.Context, name, description string, allocation int) (*ticket.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicketOption", ctx, name, description, allocation)
	ret0, _ := ret[0].(*ticket.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicketOption indicates an expected call of CreateTicketOption.
func (mr *MockRepositoryMockRecorder) CreateTicketOption(ctx, name, description, allocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicketOption", reflect.TypeOf((*MockRepository)(nil).CreateTicketOption), ctx, name, description, allocation)
}

// GetTicket mocks base method.
func (m *MockRepository) GetTicket(ctx context.Context, id int) (*ticket.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicket", ctx, id)
	ret0, _ := ret[0].(*ticket.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicket indicates an expected call of GetTicket.
func (mr *MockRepositoryMockRecorder) GetTicket(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicket", reflect.TypeOf((*MockRepository)(nil).GetTicket), ctx, id)
}

// PurchaseFromTicketOption mocks base method.
func (m *MockRepository) PurchaseFromTicketOption(ctx context.Context, id, quantity int, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurchaseFromTicketOption", ctx, id, quantity, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurchaseFromTicketOption indicates an expected call of PurchaseFromTicketOption.
func (mr *MockRepositoryMockRecorder) PurchaseFromTicketOption(ctx, id, quantity, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurchaseFromTicketOption", reflect.TypeOf((*MockRepository)(nil).PurchaseFromTicketOption), ctx, id, quantity, userID)
}
